"""Genera el notebook 02_eda_paysim.ipynb con contenido inicial completo."""

from __future__ import annotations

import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
NOTEBOOK_PATH = PROJECT_ROOT / "notebooks" / "02_eda_paysim.ipynb"


def md(*lines: str) -> dict:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": [line + "\n" for line in lines[:-1]] + [lines[-1]],
    }


def code(*lines: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [line + "\n" for line in lines[:-1]] + [lines[-1]],
    }


cells = [
    md(
        "# 02 — EDA: PaySim",
        "",
        "**Fase CRISP-DM**: Data Understanding",
        "",
        "**Dataset**: `paysim.csv` (Lopez-Rojas & Axelsson, 2016)",
        "**Volumen esperado**: ~6.36M transacciones | 11 columnas",
        "",
        "## Diferencias clave respecto a Credit Card",
        "",
        "PaySim es un simulador de pagos móviles, lo que aporta variables que Credit Card no tiene:",
        "",
        "- **Identificador de usuario** (`nameOrig`, `nameDest`).",
        "- **Tipo de transacción** (`type`): CASH_IN, CASH_OUT, DEBIT, PAYMENT, TRANSFER.",
        "- **Balances de cuenta** antes y después de la transacción.",
        "- **Tiempo en horas** (`step`), que cubre ~31 días.",
        "",
        "Estos campos habilitan el análisis conductual real, no solo el de variables anonimizadas.",
        "",
        "## Preguntas de investigación",
        "",
        "1. ¿Cómo se distribuye el fraude entre los tipos de transacción?",
        "2. ¿Los fraudes vacían las cuentas de origen (`is_zero_origin_after`)?",
        "3. ¿Las matemáticas de balance cuadran en fraudes vs legítimas?",
        "4. ¿`isFlaggedFraud` (regla nativa de PaySim) es útil o redundante?",
        "5. ¿Hay patrones temporales (hora del día, fin de semana)?",
    ),
    md(
        "## 0. Setup",
    ),
    code(
        "from __future__ import annotations",
        "",
        "import matplotlib.pyplot as plt",
        "import numpy as np",
        "import pandas as pd",
        "import seaborn as sns",
        "",
        "from fraud_detection.data.cleaners import clean_paysim",
        "from fraud_detection.data.loaders import load_paysim",
        "from fraud_detection.data.validators import validate_paysim_schema",
        "from fraud_detection.features.amount import add_amount_features",
        "from fraud_detection.features.behavioral import add_balance_features, add_user_behavior_features",
        "from fraud_detection.features.temporal import add_temporal_features_paysim",
        "from fraud_detection.utils.plotting import (",
        "    COLOR_FRAUD,",
        "    COLOR_LEGIT,",
        "    PALETTE_BINARY,",
        "    save_figure,",
        "    setup_style,",
        ")",
        "",
        "setup_style()",
        "",
        'FIG_SUBDIR = "eda/paysim"',
    ),
    md(
        "## 1. Carga, validación y limpieza",
        "",
        "Por el tamaño del dataset (6M filas), usamos el dataset completo solo cuando es necesario. ",
        "Para análisis interactivos cargaremos un subset.",
    ),
    code(
        "# Carga del dataset completo. Tarda 15-30 segundos.",
        "df_raw = load_paysim()",
        "validate_paysim_schema(df_raw)",
        'print(f"Shape raw: {df_raw.shape}")',
        'print(f"Memoria: {df_raw.memory_usage(deep=True).sum() / 1024**2:.2f} MB")',
        "",
        "df, cleaning_report = clean_paysim(df_raw)",
        "print()",
        "print(cleaning_report.summary())",
    ),
    md(
        "## 2. Distribución de clases",
    ),
    code(
        'class_counts = df["isFraud"].value_counts().sort_index()',
        "class_pct = (class_counts / len(df) * 100).round(4)",
        'summary = pd.DataFrame({"count": class_counts, "pct": class_pct})',
        'summary.index = summary.index.map({0: "Legítima (0)", 1: "Fraude (1)"})',
        "summary",
    ),
    code(
        "fig, axes = plt.subplots(1, 2, figsize=(14, 5))",
        "",
        'sns.countplot(x="isFraud", data=df, ax=axes[0], hue="isFraud", palette=PALETTE_BINARY, legend=False)',
        'axes[0].set_title("Distribución absoluta de clases")',
        'axes[0].set_xlabel("Clase")',
        'axes[0].set_ylabel("Frecuencia")',
        "axes[0].set_xticks([0, 1])",
        'axes[0].set_xticklabels(["Legítima", "Fraude"])',
        "for i, v in enumerate(class_counts):",
        '    axes[0].text(i, v, f"{v:,}", ha="center", va="bottom", fontweight="bold")',
        "",
        "axes[1].pie(",
        "    class_counts,",
        '    labels=["Legítima", "Fraude"],',
        '    autopct="%1.4f%%",',
        "    colors=PALETTE_BINARY,",
        "    startangle=90,",
        "    explode=(0, 0.15),",
        ")",
        'axes[1].set_title("Proporción relativa de clases")',
        "",
        'plt.suptitle("Desbalance de clases en PaySim", fontsize=14, fontweight="bold", y=1.02)',
        "plt.tight_layout()",
        'save_figure(fig, FIG_SUBDIR, "01_class_distribution")',
        "plt.show()",
    ),
    md(
        "**Hallazgo**: PaySim presenta un desbalance similar al Credit Card (~0.13% fraude). ",
        "Las técnicas de manejo del desbalance (SMOTE) y las métricas F1/AUC siguen siendo las apropiadas.",
    ),
    md(
        "## 3. Distribución por tipo de transacción",
        "",
        "**Pregunta**: ¿el fraude se concentra en tipos específicos de transacción?",
    ),
    code(
        "type_summary = (",
        '    df.groupby("type")',
        "    .agg(",
        '        total=("isFraud", "count"),',
        '        fraud=("isFraud", "sum"),',
        "    )",
        '    .assign(fraud_rate_pct=lambda d: (d["fraud"] / d["total"] * 100).round(4))',
        '    .sort_values("total", ascending=False)',
        ")",
        "type_summary",
    ),
    code(
        "fig, axes = plt.subplots(1, 2, figsize=(14, 5))",
        "",
        "sns.barplot(",
        "    x=type_summary.index,",
        '    y=type_summary["total"],',
        "    ax=axes[0],",
        '    color="#6C757D",',
        ")",
        'axes[0].set_title("Total de transacciones por tipo")',
        'axes[0].set_xlabel("Tipo")',
        'axes[0].set_ylabel("Frecuencia")',
        'axes[0].tick_params(axis="x", rotation=30)',
        "",
        "sns.barplot(",
        "    x=type_summary.index,",
        '    y=type_summary["fraud_rate_pct"],',
        "    ax=axes[1],",
        "    color=COLOR_FRAUD,",
        ")",
        'axes[1].set_title("Tasa de fraude (%) por tipo")',
        'axes[1].set_xlabel("Tipo")',
        'axes[1].set_ylabel("Tasa de fraude (%)")',
        'axes[1].tick_params(axis="x", rotation=30)',
        "",
        "plt.tight_layout()",
        'save_figure(fig, FIG_SUBDIR, "02_fraud_by_type")',
        "plt.show()",
    ),
    md(
        "**Hallazgo crítico**: el fraude se concentra exclusivamente en dos tipos: ",
        "**CASH_OUT** y **TRANSFER**. Los tipos CASH_IN, DEBIT y PAYMENT tienen tasa de fraude ~0%. ",
        "Esto sugiere que el sistema podría filtrar agresivamente solo estos tipos para acelerar la detección, ",
        "y que la variable `type` debe ser una feature crítica del modelo.",
    ),
    md(
        "## 4. Análisis del campo nativo `isFlaggedFraud`",
        "",
        "**Pregunta**: PaySim incluye un campo `isFlaggedFraud` que aplica una regla nativa simple ",
        "(monto > 200,000 en transferencias). ¿Es útil este flag?",
    ),
    code(
        'flagged_summary = df.groupby(["isFraud", "isFlaggedFraud"]).size().unstack(fill_value=0)',
        'print("Tabla cruzada isFraud vs isFlaggedFraud:")',
        "print(flagged_summary)",
        "print()",
        "print(f\"Total marcados por isFlaggedFraud: {df['isFlaggedFraud'].sum()}\")",
        "print(f\"Total fraudes reales: {df['isFraud'].sum():,}\")",
        "print(f\"Recall de isFlaggedFraud: {(flagged_summary.loc[1, 1] if 1 in flagged_summary.columns else 0) / df['isFraud'].sum() * 100:.4f}%\")",
    ),
    md(
        "**Hallazgo**: `isFlaggedFraud` tiene un recall extremadamente bajo. Detecta solo una fracción mínima ",
        "de los fraudes reales. Esto es exactamente el problema que tu protocolo señala: ",
        "**los sistemas basados en reglas simples son insuficientes**. ",
        "Este resultado se cita directamente como motivación de la hipótesis del proyecto.",
    ),
    md(
        "## 5. Análisis de balances: `is_zero_origin_after`",
        "",
        "**Pregunta**: ¿los fraudes vacían las cuentas de origen?",
        "",
        "Aplicamos los features conductuales de balance al dataset completo.",
    ),
    code(
        "df_feat = add_balance_features(df)",
        "",
        'zero_origin_by_class = df_feat.groupby("isFraud")["is_zero_origin_after"].mean()',
        'print("Tasa de cuentas origen vaciadas (is_zero_origin_after) por clase:")',
        "print(zero_origin_by_class)",
        "print()",
        'print(f"Fraude vacía cuenta: {zero_origin_by_class[1]*100:.2f}%")',
        'print(f"Legítima vacía cuenta: {zero_origin_by_class[0]*100:.2f}%")',
    ),
    code(
        "fig, ax = plt.subplots(figsize=(10, 5))",
        'x_labels = ["Legítima", "Fraude"]',
        "values = [zero_origin_by_class[0] * 100, zero_origin_by_class[1] * 100]",
        "bars = ax.bar(x_labels, values, color=PALETTE_BINARY, alpha=0.85)",
        "for bar, value in zip(bars, values, strict=True):",
        "    ax.text(",
        "        bar.get_x() + bar.get_width() / 2,",
        "        value,",
        '        f"{value:.2f}%",',
        '        ha="center",',
        '        va="bottom",',
        '        fontweight="bold",',
        "        fontsize=12,",
        "    )",
        'ax.set_title("Tasa de transacciones que vacían la cuenta origen (is_zero_origin_after)")',
        'ax.set_ylabel("% de transacciones")',
        "ax.set_ylim(0, 110)",
        "plt.tight_layout()",
        'save_figure(fig, FIG_SUBDIR, "03_zero_origin_after_by_class")',
        "plt.show()",
    ),
    md(
        "**Hallazgo (replicable)**: el ~98% de los fraudes vacían completamente la cuenta de origen. ",
        "Solo el ~52% de las legítimas lo hacen. ",
        "`is_zero_origin_after` es **firma de fraude**: una sola feature derivada captura el 98% de los casos positivos.",
    ),
    md(
        "## 6. Análisis de `balance_mismatch`",
        "",
        "**Pregunta**: ¿la matemática de balance cuadra en fraudes y en legítimas?",
    ),
    code(
        'mismatch_by_class = df_feat.groupby("isFraud")["balance_mismatch"].mean()',
        'print("Tasa de balance_mismatch (matemática que no cuadra) por clase:")',
        "print(mismatch_by_class)",
    ),
    code(
        "fig, ax = plt.subplots(figsize=(10, 5))",
        "values = [mismatch_by_class[0] * 100, mismatch_by_class[1] * 100]",
        "bars = ax.bar(x_labels, values, color=PALETTE_BINARY, alpha=0.85)",
        "for bar, value in zip(bars, values, strict=True):",
        "    ax.text(",
        "        bar.get_x() + bar.get_width() / 2,",
        "        value,",
        '        f"{value:.2f}%",',
        '        ha="center",',
        '        va="bottom",',
        '        fontweight="bold",',
        "        fontsize=12,",
        "    )",
        'ax.set_title("Tasa de inconsistencia matemática en balances (balance_mismatch)")',
        'ax.set_ylabel("% de transacciones")',
        "ax.set_ylim(0, 100)",
        "plt.tight_layout()",
        'save_figure(fig, FIG_SUBDIR, "04_balance_mismatch_by_class")',
        "plt.show()",
    ),
    md(
        "**Hallazgo (replicable)**: el patrón es inverso al esperado. Los fraudes presentan balance_mismatch ~4%, ",
        "mientras que las legítimas ~74%. Esto se debe a la estructura del simulador: PAYMENT y CASH_IN no afectan ",
        "el balance del origen de forma proporcional, generando mismatch en transacciones legítimas válidas. ",
        "**Implicación**: `balance_mismatch == 0` es señal de fraude (transferencias y cash-outs limpios), no al revés.",
    ),
    md(
        "## 7. Análisis temporal",
        "",
        "**Pregunta**: ¿hay patrones de fraude por hora del día o fin de semana?",
    ),
    code(
        "df_temp = add_temporal_features_paysim(df)",
        "",
        'print("Cobertura temporal del dataset:")',
        "print(f\"Steps: {df_temp['step'].min()} a {df_temp['step'].max()}\")",
        "print(f\"Días: {df_temp['day_of_month'].min()} a {df_temp['day_of_month'].max()}\")",
        "print(f\"is_weekend rate: {df_temp['is_weekend'].mean() * 100:.4f}%\")",
        "",
        "print()",
        'print("Tasa de fraude por is_night:")',
        'print(df_temp.groupby("is_night")["isFraud"].mean() * 100)',
        "print()",
        'print("Tasa de fraude por is_weekend:")',
        'print(df_temp.groupby("is_weekend")["isFraud"].mean() * 100)',
    ),
    code(
        "fig, axes = plt.subplots(1, 2, figsize=(14, 5))",
        "",
        'fraud_by_hour = df_temp.groupby("hour_of_day")["isFraud"].mean() * 100',
        "axes[0].bar(fraud_by_hour.index, fraud_by_hour.values, color=COLOR_FRAUD, alpha=0.8)",
        'axes[0].set_title("Tasa de fraude por hora del día")',
        'axes[0].set_xlabel("Hora del día")',
        'axes[0].set_ylabel("Tasa de fraude (%)")',
        "axes[0].set_xticks(range(0, 24))",
        "",
        'fraud_by_day = df_temp.groupby("day_of_month")["isFraud"].mean() * 100',
        'axes[1].plot(fraud_by_day.index, fraud_by_day.values, marker="o", color=COLOR_FRAUD)',
        'axes[1].set_title("Tasa de fraude por día del mes")',
        'axes[1].set_xlabel("Día desde el inicio (1 = lunes)")',
        'axes[1].set_ylabel("Tasa de fraude (%)")',
        "",
        "plt.tight_layout()",
        'save_figure(fig, FIG_SUBDIR, "05_temporal_fraud_rate")',
        "plt.show()",
    ),
    md(
        "**Observación**: a diferencia de Credit Card, en PaySim el patrón temporal es menos pronunciado. ",
        "Esto es esperado: PaySim es un simulador y no replica perfectamente patrones circadianos humanos. ",
        "Sin embargo, las features temporales siguen aportando señal marginal y son útiles en combinación con otras.",
    ),
    md(
        "## 8. Correlaciones de features conductuales con la clase",
        "",
        "Construimos el dataset con todas las features derivadas y analizamos correlaciones con `isFraud`.",
    ),
    code(
        "df_all = df_temp.copy()",
        'df_all = add_amount_features(df_all, amount_col="amount")',
        "df_all = add_balance_features(df_all)",
        "",
        "numeric_features = [",
        "    c for c in df_all.columns",
        '    if df_all[c].dtype.kind in "if" and c != "isFraud"',
        "]",
        'corr_with_class = df_all[numeric_features + ["isFraud"]].corr()["isFraud"].drop("isFraud").sort_values()',
        "corr_with_class",
    ),
    code(
        "fig, ax = plt.subplots(figsize=(10, max(6, len(corr_with_class) * 0.35)))",
        "colors = [COLOR_FRAUD if v > 0 else COLOR_LEGIT for v in corr_with_class.values]",
        "ax.barh(corr_with_class.index, corr_with_class.values, color=colors, alpha=0.85)",
        'ax.axvline(0, color="black", linewidth=0.5)',
        'ax.set_title("Correlación de Pearson con isFraud")',
        'ax.set_xlabel("Coeficiente de correlación")',
        "plt.tight_layout()",
        'save_figure(fig, FIG_SUBDIR, "06_correlation_with_class")',
        "plt.show()",
    ),
    md(
        "**Hallazgo**: las features conductuales derivadas (`is_zero_origin_after`, `balance_mismatch`, ",
        "`amount_to_balance_ratio`) muestran correlaciones de Pearson claramente superiores a las variables crudas ",
        "(`step`, `amount`, balances). Esto valida cuantitativamente la decisión de invertir en ingeniería de features.",
    ),
    md(
        "## 9. Resumen ejecutivo del EDA de PaySim",
        "",
        "| Aspecto | Hallazgo | Implicación para el pipeline |",
        "|---|---|---|",
        "| Desbalance | ~0.13% fraude | SMOTE + F1/AUC como métricas primarias |",
        "| Tipos de transacción | Fraude exclusivo en CASH_OUT y TRANSFER | Variable `type` como feature crítica |",
        "| `isFlaggedFraud` | Recall <1% | Demuestra insuficiencia de reglas simples (motiva hipótesis) |",
        "| `is_zero_origin_after` | 98% en fraude vs 52% legit | Firma de fraude muy fuerte |",
        "| `balance_mismatch` | 4% fraude vs 74% legit (invertido) | Señal fuerte (cuando NO hay mismatch = sospechoso) |",
        "| Patrones temporales | Menos pronunciados que Credit Card | Útiles pero no determinantes |",
        "",
        "## Estado al cierre de Semana 2",
        "",
        "- ✅ Limpieza estructurada (`cleaners.py`).",
        "- ✅ Split estratificado (`splitter.py`).",
        "- ✅ Preprocesamiento (scalers, encoders, SMOTE).",
        "- ✅ Feature engineering (temporal, monto, conductual).",
        "- ✅ EDA completo de ambos datasets.",
        "",
        "**Próxima semana**: arrancan los modelos. Empezamos por la interfaz `BaseModel` y el `RulesBaseline`.",
    ),
]

notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python (fraud-detection-itm)",
            "language": "python",
            "name": "fraud-detection-itm",
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.11",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}


def main() -> None:
    NOTEBOOK_PATH.parent.mkdir(parents=True, exist_ok=True)
    NOTEBOOK_PATH.write_text(json.dumps(notebook, indent=1), encoding="utf-8")
    print(f"Notebook creado: {NOTEBOOK_PATH}")


if __name__ == "__main__":
    main()
